// Code generated by "stringer -type=SuitType"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bastoni-0]
	_ = x[Coppe-1]
	_ = x[Denari-2]
	_ = x[Spade-3]
	_ = x[Quadri-4]
	_ = x[Fiori-5]
	_ = x[Cuori-6]
	_ = x[Picche-7]
	_ = x[Jolly-8]
}

const _SuitType_name = "BastoniCoppeDenariSpadeQuadriFioriCuoriPiccheJolly"

var _SuitType_index = [...]uint8{0, 7, 12, 18, 23, 29, 34, 39, 45, 50}

func (i SuitType) String() string {
	if i < 0 || i >= SuitType(len(_SuitType_index)-1) {
		return "SuitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SuitType_name[_SuitType_index[i]:_SuitType_index[i+1]]
}
